{{- if and .Values.metrics.enabled .Values.metrics.prometheusRule.enabled }}
{{- include "bjw-s.common.values.init" . -}}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}
  labels:
    {{- include "bjw-s.common.lib.metadata.allLabels" . | nindent 4 }}
    {{- with .Values.metrics.prometheusRule.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  groups:
    - name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}
      rules:
        - alert: UnifiPollerAbsent
          annotations:
            description: Unifi Poller has disappeared from Prometheus service discovery.
            summary: Unifi Poller is down.
          expr: |
            absent(up{job=~".*{{ include "bjw-s.common.lib.chart.names.fullname" . }}.*"} == 1)
          for: 5m
          labels:
            severity: critical
        {{- with .Values.metrics.prometheusRule.rules }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}
