{{- if .Values.metrics.enabled }}
{{- include "j0sh3rs.common.values.init" . -}}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "j0sh3rs.common.lib.chart.names.fullname" . }}
  labels:
    {{- include "j0sh3rs.common.lib.metadata.allLabels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "j0sh3rs.common.lib.metadata.allLabels.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      {{- with .Values.metrics.serviceMonitor.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      path: /metrics
{{- end }}
