#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/j0sh3rs/helm-charts/tree/main/charts/library/common/values.yaml
#

image:
  # -- image repository
  repository: shenxn/protonmail-bridge
  # -- image tag
  tag: build
  # -- image pull policy
  pullPolicy: Always

# -- environment variables.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: America/New_York

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        enabled: false
      smtp:
        enabled: true
        protocol: TCP
        port: 25

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    mountPath: /root
