---
apiVersion: v1
description: A chart for a Cadvisor deployment
name: cadvisor
version: 1.0.0
appVersion: 0.46.0
home: https://github.com/google/cadvisor
sources:
  - https://github.com/google/cadvisor
  - https://github.com/j0sh3rs/helm-charts
keywords:
  - prometheus
  - cadvisor
  - monitoring
maintainers:
  - name: j0sh3rs
    email: j0sh3rs@pm.me
annotations:
  artifacthub.io/changes: |-
    - kind: added
      description: Initial Deployment of new chart version
