apiVersion: v1
kind: Service
metadata:
  name: {{ template "cadvisor.name" . }}
  labels:
    app: {{ template "cadvisor.name" . }}
    chart: {{ template "cadvisor.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/probe: 'true'
    prometheus.io/port: {{ .Values.container.port }}
spec:
  ports:
  - name: http
    port: {{ .Values.container.port }}
    targetPort: {{ .Values.container.port }}
    protocol: TCP
  selector:
    app: {{ template "cadvisor.name" . }}
  type: ClusterIP
