---
apiVersion: v2
appVersion: 2.1.3
description: Collect ALL UniFi Controller, Site, Device & Client Data - Export to InfluxDB or Prometheus
name: unifi-poller
version: 1.0.1
kubeVersion: '>=1.22.0-0'
keywords:
  - unifi
  - unifi-poller
home: https://github.com/j0sh3rs/charts/tree/master/charts/library/unifi-poller
icon: https://raw.githubusercontent.com/wiki/unifi-poller/unifi-poller/images/unifi-poller-logo.png
sources:
  - https://github.com/unifi-poller/unifi-poller
  - https://hub.docker.com/r/golift/unifi-poller
maintainers:
  - name: j0sh3rs
    email: j0sh3rs@pm.me
dependencies:
  - name: common
    repository: https://j0sh3rs.github.io/helm-charts
    version: 1.2.1
annotations:
  artifacthub.io/changes: |-
    - kind: added
      description: Initial Deployment of new chart version
