{{- include "bjw-s.common.values.init" . -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}-config
  labels:
    {{- include "bjw-s.common.lib.metadata.allLabels" . | nindent 4 }}
data:
  config.yml: |
    {{- .Values.config | nindent 4 }}
