{{- if and .Values.metrics.enabled .Values.metrics.prometheusRule.enabled }}
{{- include "j0sh3rs.common.values.init" . -}}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "j0sh3rs.common.lib.chart.names.fullname" . }}
  labels:
    {{- include "j0sh3rs.common.lib.metadata.allLabels" . | nindent 4 }}
    {{- with .Values.metrics.prometheusRule.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  groups:
    - name: {{ include "j0sh3rs.common.lib.chart.names.fullname" . }}
      rules:
        - alert: BlockyAbsent
          annotations:
            description: Blocky has disappeared from Prometheus service discovery.
            summary: Blocky is down.
          expr: |
            absent(up{job=~".*{{ include "j0sh3rs.common.lib.chart.names.fullname" . }}.*"} == 1)
          for: 5m
          labels:
            severity: critical
        - alert: BlockyDisabled
          annotations:
            description: Blocky's ad blocking has been disabled for 15min.
              Please re-enable protection.
            summary: Blocky is disabled.
          expr: |
            blocky_blocking_enabled{job=~".*{{ include "j0sh3rs.common.lib.chart.names.fullname" . }}.*"} == 0
          for: 15m
          labels:
            severity: critical
        {{- with .Values.metrics.prometheusRule.rules }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}
